runtime: custom
env_variables:
  BUCKET_NAME: "webpage-production-bucket"
env: flex
resources:
  memory_gb: 1.0
manual_scaling:
  instances: 1
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: auto
  secure: always