runtime: nodejs10
instance_class: F1
entrypoint: "npm run ssr"
env_variables:
  BUCKET_NAME: "webpage-production-bucket"
resources:
  memory_gb: 0.6
handlers:
- url: /
  static_dir: build
  http_headers:
    Access-Control-Allow-Origin: "*"
- url: /.*
  script: auto
  secure: always